import { ErrorFilter } from './error-response.interface.js';

export const ErrorCode = {
  AUTH_LOGIN_FAILED: { code: 'FLEET-AUTH001', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Invalid username or password.' },
  AUTH_ACCOUNT_INACTIVE: { code: 'FLEET-AUTH002', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Your account has been deactivated. Please contact an administrator.' },
  AUTH_TOKEN_MISSING: { code: 'FLEET-AUTH003', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Authentication required. Please log in.' },
  AUTH_TOKEN_INVALID: { code: 'FLEET-AUTH004', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Your session has expired. Please log in again.' },
  AUTH_PERMISSION_DENIED: { code: 'FLEET-AUTH005', filter: ErrorFilter.USER_NOT_AUTHORIZED, description: 'You do not have permission to perform this action.' },
  AUTH_TOO_MANY_ATTEMPTS: { code: 'FLEET-AUTH006', filter: ErrorFilter.RATE_LIMIT_EXCEEDED, description: 'Too many failed sign-in attempts. Please wait a few minutes and try again.' },

  USR_DUPLICATE_EMAIL: { code: 'FLEET-USR001', filter: ErrorFilter.INVALID_REQUEST, description: 'A user with this email already exists.' },
  USR_DUPLICATE_USERNAME: { code: 'FLEET-USR002', filter: ErrorFilter.INVALID_REQUEST, description: 'A user with this username already exists.' },
  USR_NOT_FOUND: { code: 'FLEET-USR003', filter: ErrorFilter.INVALID_REQUEST, description: 'User not found.' },
  USR_CREATE_FAILED: { code: 'FLEET-USR004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create user. Please try again.' },
  USR_UPDATE_FAILED: { code: 'FLEET-USR005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update user. Please try again.' },
  USR_DELETE_FAILED: { code: 'FLEET-USR006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete user. Please try again.' },
  USR_FETCH_FAILED: { code: 'FLEET-USR007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve users. Please try again.' },
  USR_CANNOT_REMOVE_SELF: { code: 'FLEET-USR009', filter: ErrorFilter.USER_END_VIOLATION, description: 'You cannot delete or deactivate your own account.' },
  USR_PASSWORD_TOO_SHORT: { code: 'FLEET-USR010', filter: ErrorFilter.INVALID_REQUEST, description: 'Password must be at least 8 characters long.' },
  USR_LANGUAGE_UPDATE_FAILED: { code: 'FLEET-USR008', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update language preference. Please try again.' },

  TRK_NOT_FOUND: { code: 'FLEET-TRK001', filter: ErrorFilter.INVALID_REQUEST, description: 'Truck not found.' },
  TRK_IN_USE: { code: 'FLEET-TRK002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This truck is used by one or more trips and cannot be deleted.' },
  TRK_CREATE_FAILED: { code: 'FLEET-TRK003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create truck. Please try again.' },
  TRK_UPDATE_FAILED: { code: 'FLEET-TRK004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update truck. Please try again.' },
  TRK_DELETE_FAILED: { code: 'FLEET-TRK005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete truck. Please try again.' },
  TRK_FETCH_FAILED: { code: 'FLEET-TRK006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve trucks. Please try again.' },
  TRK_ASSIGNMENT_NOT_FOUND: { code: 'FLEET-TRK007', filter: ErrorFilter.INVALID_REQUEST, description: 'Truck assignment not found.' },
  TRK_ASSIGNMENT_OVERLAP: { code: 'FLEET-TRK008', filter: ErrorFilter.USER_END_VIOLATION, description: 'This truck already has an assignment during the selected period.' },
  TRK_ASSIGNMENT_INVALID_DATES: { code: 'FLEET-TRK009', filter: ErrorFilter.INVALID_REQUEST, description: 'The end date must be on or after the start date.' },
  TRK_ASSIGNMENT_FETCH_FAILED: { code: 'FLEET-TRK010', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve truck assignments. Please try again.' },
  TRK_ASSIGNMENT_CREATE_FAILED: { code: 'FLEET-TRK011', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create truck assignment. Please try again.' },
  TRK_ASSIGNMENT_UPDATE_FAILED: { code: 'FLEET-TRK012', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update truck assignment. Please try again.' },
  TRK_ASSIGNMENT_DELETE_FAILED: { code: 'FLEET-TRK013', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to remove truck assignment. Please try again.' },

  DRV_NOT_FOUND: { code: 'FLEET-DRV001', filter: ErrorFilter.INVALID_REQUEST, description: 'Driver not found.' },
  DRV_IN_USE: { code: 'FLEET-DRV002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This driver is used by one or more trips and cannot be deleted.' },
  DRV_CREATE_FAILED: { code: 'FLEET-DRV003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create driver. Please try again.' },
  DRV_UPDATE_FAILED: { code: 'FLEET-DRV004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update driver. Please try again.' },
  DRV_DELETE_FAILED: { code: 'FLEET-DRV005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete driver. Please try again.' },
  DRV_FETCH_FAILED: { code: 'FLEET-DRV006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve drivers. Please try again.' },
  DRV_HAS_ASSIGNMENTS: { code: 'FLEET-DRV007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This driver has truck assignments and cannot be deleted.' },

  CUS_NOT_FOUND: { code: 'FLEET-CUS001', filter: ErrorFilter.INVALID_REQUEST, description: 'Customer not found.' },
  CUS_IN_USE: { code: 'FLEET-CUS002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This customer is used by one or more trips and cannot be deleted.' },
  CUS_CREATE_FAILED: { code: 'FLEET-CUS003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create customer. Please try again.' },
  CUS_UPDATE_FAILED: { code: 'FLEET-CUS004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update customer. Please try again.' },
  CUS_DELETE_FAILED: { code: 'FLEET-CUS005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete customer. Please try again.' },
  CUS_FETCH_FAILED: { code: 'FLEET-CUS006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve customers. Please try again.' },

  SUP_NOT_FOUND: { code: 'FLEET-SUP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Supplier not found.' },
  SUP_IN_USE: { code: 'FLEET-SUP002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This supplier is used by one or more rate contracts and cannot be deleted.' },
  SUP_CREATE_FAILED: { code: 'FLEET-SUP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create supplier. Please try again.' },
  SUP_UPDATE_FAILED: { code: 'FLEET-SUP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update supplier. Please try again.' },
  SUP_DELETE_FAILED: { code: 'FLEET-SUP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete supplier. Please try again.' },
  SUP_FETCH_FAILED: { code: 'FLEET-SUP006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve suppliers. Please try again.' },

  LOC_NOT_FOUND: { code: 'FLEET-LOC001', filter: ErrorFilter.INVALID_REQUEST, description: 'Location not found.' },
  LOC_IN_USE: { code: 'FLEET-LOC002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This location is used by one or more trips and cannot be deleted.' },
  LOC_CREATE_FAILED: { code: 'FLEET-LOC003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create location. Please try again.' },
  LOC_UPDATE_FAILED: { code: 'FLEET-LOC004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update location. Please try again.' },
  LOC_DELETE_FAILED: { code: 'FLEET-LOC005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete location. Please try again.' },
  LOC_FETCH_FAILED: { code: 'FLEET-LOC006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve locations. Please try again.' },

  CGO_NOT_FOUND: { code: 'FLEET-CGO001', filter: ErrorFilter.INVALID_REQUEST, description: 'Cargo type not found.' },
  CGO_IN_USE: { code: 'FLEET-CGO002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This cargo type is used by one or more trips and cannot be deleted.' },
  CGO_CREATE_FAILED: { code: 'FLEET-CGO003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create cargo type. Please try again.' },
  CGO_UPDATE_FAILED: { code: 'FLEET-CGO004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update cargo type. Please try again.' },
  CGO_DELETE_FAILED: { code: 'FLEET-CGO005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete cargo type. Please try again.' },
  CGO_FETCH_FAILED: { code: 'FLEET-CGO006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve cargo types. Please try again.' },

  TRP_NOT_FOUND: { code: 'FLEET-TRP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Trip not found.' },
  TRP_INVALID_RELATIONS: { code: 'FLEET-TRP002', filter: ErrorFilter.INVALID_REQUEST, description: 'One or more referenced records do not exist.' },
  TRP_CREATE_FAILED: { code: 'FLEET-TRP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create trip. Please try again.' },
  TRP_UPDATE_FAILED: { code: 'FLEET-TRP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update trip. Please try again.' },
  TRP_DELETE_FAILED: { code: 'FLEET-TRP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete trip. Please try again.' },
  TRP_FETCH_FAILED: { code: 'FLEET-TRP006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve trips. Please try again.' },
  TRP_DUPLICATE_TRANSACTION: { code: 'FLEET-TRP007', filter: ErrorFilter.INVALID_REQUEST, description: 'A trip with this transaction number already exists.' },
  TRP_NO_DRIVER_ASSIGNED: { code: 'FLEET-TRP008', filter: ErrorFilter.INVALID_REQUEST, description: 'No driver is currently assigned to this truck for the selected trip date.' },

  INV_NOT_FOUND: { code: 'FLEET-INV001', filter: ErrorFilter.INVALID_REQUEST, description: 'Invoice not found.' },
  INV_STATUS_CONFLICT: { code: 'FLEET-INV002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This action cannot be performed on the current invoice status.' },
  INV_CREATE_FAILED: { code: 'FLEET-INV003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create invoice. Please try again.' },
  INV_UPDATE_FAILED: { code: 'FLEET-INV004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update invoice. Please try again.' },
  INV_DELETE_FAILED: { code: 'FLEET-INV005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete invoice. Please try again.' },
  INV_FETCH_FAILED: { code: 'FLEET-INV006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve invoices. Please try again.' },

  RLC_NOT_FOUND: { code: 'FLEET-RLC001', filter: ErrorFilter.INVALID_REQUEST, description: 'Rate contract not found.' },
  RLC_DUPLICATE: { code: 'FLEET-RLC002', filter: ErrorFilter.INVALID_REQUEST, description: 'A rate contract with this reference already exists.' },
  RLC_CREATE_FAILED: { code: 'FLEET-RLC003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create rate contract. Please try again.' },
  RLC_UPDATE_FAILED: { code: 'FLEET-RLC004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update rate contract. Please try again.' },
  RLC_DELETE_FAILED: { code: 'FLEET-RLC005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete rate contract. Please try again.' },
  RLC_FETCH_FAILED: { code: 'FLEET-RLC006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve rate contracts. Please try again.' },

  LDO_BATCH_NOT_FOUND: { code: 'FLEET-LDO002', filter: ErrorFilter.INVALID_REQUEST, description: 'Loading order batch not found.' },
  LDO_CREATE_FAILED: { code: 'FLEET-LDO003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create loading order. Please try again.' },
  LDO_DELETE_FAILED: { code: 'FLEET-LDO005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete loading order. Please try again.' },
  LDO_FETCH_FAILED: { code: 'FLEET-LDO006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve loading orders. Please try again.' },

  SPP_NOT_FOUND: { code: 'FLEET-SPP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Supplier payment not found.' },
  SPP_CREATE_FAILED: { code: 'FLEET-SPP002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create supplier payment. Please try again.' },
  SPP_UPDATE_FAILED: { code: 'FLEET-SPP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update supplier payment. Please try again.' },
  SPP_DELETE_FAILED: { code: 'FLEET-SPP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete supplier payment. Please try again.' },
  SPP_FETCH_FAILED: { code: 'FLEET-SPP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve supplier payments. Please try again.' },

  ROL_NOT_FOUND: { code: 'FLEET-ROL001', filter: ErrorFilter.INVALID_REQUEST, description: 'Role not found.' },
  ROL_HAS_USERS: { code: 'FLEET-ROL002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This role is assigned to one or more users and cannot be deleted.' },
  ROL_CREATE_FAILED: { code: 'FLEET-ROL004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create role. Please try again.' },
  ROL_UPDATE_FAILED: { code: 'FLEET-ROL005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update role. Please try again.' },
  ROL_DELETE_FAILED: { code: 'FLEET-ROL006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete role. Please try again.' },
  ROL_PROTECTED: { code: 'FLEET-ROL008', filter: ErrorFilter.USER_END_VIOLATION, description: 'The ADMIN role is built in and cannot be renamed or deleted.' },
  ROL_UNKNOWN_MODULE: { code: 'FLEET-ROL009', filter: ErrorFilter.INVALID_REQUEST, description: 'The permission matrix contains an unknown module.' },
  ROL_FETCH_FAILED: { code: 'FLEET-ROL007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve roles. Please try again.' },

  DSH_FETCH_FAILED: { code: 'FLEET-DSH001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load dashboard data. Please try again.' },

  SET_FETCH_FAILED: { code: 'FLEET-SET001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve company settings. Please try again.' },
  SET_UPDATE_FAILED: { code: 'FLEET-SET002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update company settings. Please try again.' },

  WKS_NOT_FOUND: { code: 'FLEET-WKS001', filter: ErrorFilter.INVALID_REQUEST, description: 'Work order not found.' },
  WKS_CREATE_FAILED: { code: 'FLEET-WKS003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create work order. Please try again.' },
  WKS_UPDATE_FAILED: { code: 'FLEET-WKS004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update work order. Please try again.' },
  WKS_DELETE_FAILED: { code: 'FLEET-WKS005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete work order. Please try again.' },
  WKS_FETCH_FAILED: { code: 'FLEET-WKS006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve work orders. Please try again.' },
  WKS_MNT_NOT_FOUND: { code: 'FLEET-WKS007', filter: ErrorFilter.INVALID_REQUEST, description: 'Maintenance schedule not found.' },
  WKS_MNT_CREATE_FAILED: { code: 'FLEET-WKS008', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create maintenance schedule. Please try again.' },
  WKS_MNT_UPDATE_FAILED: { code: 'FLEET-WKS009', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update maintenance schedule. Please try again.' },
  WKS_MNT_DELETE_FAILED: { code: 'FLEET-WKS010', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete maintenance schedule. Please try again.' },
  WKS_MNT_FETCH_FAILED: { code: 'FLEET-WKS011', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve maintenance schedules. Please try again.' },
  WKS_INS_CREATE_FAILED: { code: 'FLEET-WKS012', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create inspection. Please try again.' },
  WKS_INS_FETCH_FAILED: { code: 'FLEET-WKS013', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve inspections. Please try again.' },
  WKS_INS_NOT_FOUND: { code: 'FLEET-WKS026', filter: ErrorFilter.INVALID_REQUEST, description: 'Inspection not found.' },
  WKS_INS_DELETE_FAILED: { code: 'FLEET-WKS021', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete inspection. Please try again.' },
  WKS_SPK_NOT_FOUND: { code: 'FLEET-WKS014', filter: ErrorFilter.INVALID_REQUEST, description: 'Spare part not found.' },
  WKS_SPK_CREATE_FAILED: { code: 'FLEET-WKS015', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create spare part. Please try again.' },
  WKS_SPK_UPDATE_FAILED: { code: 'FLEET-WKS016', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update spare part. Please try again.' },
  WKS_SPK_DELETE_FAILED: { code: 'FLEET-WKS017', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete spare part. Please try again.' },
  WKS_SPK_FETCH_FAILED: { code: 'FLEET-WKS018', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve spare parts. Please try again.' },
  WKS_SPK_LOW_STOCK: { code: 'FLEET-WKS019', filter: ErrorFilter.USER_END_VIOLATION, description: 'Insufficient stock for this spare part.' },
  WKS_SPK_TX_CREATE_FAILED: { code: 'FLEET-WKS020', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create spare part transaction. Please try again.' },
  WKS_SPK_TX_FETCH_FAILED: { code: 'FLEET-WKS025', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve spare part transactions. Please try again.' },
  WKS_EXP_CREATE_FAILED: { code: 'FLEET-WKS022', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create workshop expense. Please try again.' },
  WKS_EXP_FETCH_FAILED: { code: 'FLEET-WKS023', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve workshop expenses. Please try again.' },
  WKS_DASH_FETCH_FAILED: { code: 'FLEET-WKS024', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load workshop dashboard data. Please try again.' },

  HR_NOT_FOUND: { code: 'FLEET-HR001', filter: ErrorFilter.INVALID_REQUEST, description: 'Record not found.' },
  HR_DUPLICATE: { code: 'FLEET-HR002', filter: ErrorFilter.INVALID_REQUEST, description: 'A record with this information already exists.' },
  HR_CREATE_FAILED: { code: 'FLEET-HR003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create record. Please try again.' },
  HR_UPDATE_FAILED: { code: 'FLEET-HR004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update record. Please try again.' },
  HR_DELETE_FAILED: { code: 'FLEET-HR005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete record. Please try again.' },
  HR_FETCH_FAILED: { code: 'FLEET-HR006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve records. Please try again.' },
  HR_IN_USE: { code: 'FLEET-HR007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This record is referenced by other records and cannot be deleted.' },
  HR_ATTENDANCE_DUPLICATE: { code: 'FLEET-HR008', filter: ErrorFilter.INVALID_REQUEST, description: 'Attendance already recorded for this employee on this date.' },
  HR_LEAVE_OVERLAP: { code: 'FLEET-HR009', filter: ErrorFilter.INVALID_REQUEST, description: 'This employee already has an approved leave covering the selected dates.' },
  HR_INVALID_RELATIONS: { code: 'FLEET-HR010', filter: ErrorFilter.INVALID_REQUEST, description: 'One or more referenced records do not exist.' },

  ZATCA_NOT_CONFIGURED: { code: 'FLEET-ZATCA001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'ZATCA e-invoicing is not configured. Please complete onboarding first.' },
  ZATCA_NOT_READY: { code: 'FLEET-ZATCA002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'ZATCA onboarding is incomplete. Please complete CSID registration first.' },
  ZATCA_ALREADY_SUBMITTED: { code: 'FLEET-ZATCA003', filter: ErrorFilter.USER_END_VIOLATION, description: 'This invoice has already been submitted to ZATCA.' },
  ZATCA_SUBMIT_FAILED: { code: 'FLEET-ZATCA004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Failed to submit invoice to ZATCA. Please try again.' },
  ZATCA_XML_GENERATION_FAILED: { code: 'FLEET-ZATCA005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Failed to generate ZATCA invoice XML. Please try again.' },
  ZATCA_SIGN_FAILED: { code: 'FLEET-ZATCA006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Failed to sign ZATCA invoice. Please try again.' },
  ZATCA_REJECTED: { code: 'FLEET-ZATCA007', filter: ErrorFilter.USER_END_VIOLATION, description: 'Invoice was rejected by ZATCA. Please check the invoice data and try again.' },

  SYS_UNEXPECTED: { code: 'FLEET-SYS001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Something went wrong. Please try again.' },
  SYS_VALIDATION_ERROR: { code: 'FLEET-SYS002', filter: ErrorFilter.INVALID_REQUEST, description: 'The request contains invalid data.' },
  SYS_RATE_LIMIT: { code: 'FLEET-SYS003', filter: ErrorFilter.RATE_LIMIT_EXCEEDED, description: 'Too many requests. Please wait a moment and try again.' },
  SYS_UNKNOWN: { code: 'FLEET-SYS004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'An unexpected error occurred. Please try again.' },
  SYS_DUPLICATE: { code: 'FLEET-SYS005', filter: ErrorFilter.INVALID_REQUEST, description: 'A record with the same unique value already exists.' },
  SYS_INVALID_REFERENCE: { code: 'FLEET-SYS006', filter: ErrorFilter.INVALID_REQUEST, description: 'One of the selected related records does not exist.' },
  SYS_RECORD_IN_USE: { code: 'FLEET-SYS007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This record is used by other records and cannot be deleted.' },
  SYS_RECORD_NOT_FOUND: { code: 'FLEET-SYS008', filter: ErrorFilter.INVALID_REQUEST, description: 'The requested record no longer exists.' },
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;
