export enum ErrorFilter {
  USER_END_VIOLATION = 'USER_END_VIOLATION',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  INVALID_REQUEST = 'INVALID_REQUEST',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
}

export interface ErrorResponse {
  STATUS: 'ERROR';
  ERROR_FILTER: ErrorFilter;
  ERROR_CODE: string;
  ERROR_DESCRIPTION: string;
}
