-- HR: real file uploads for employee documents and contracts, and leave
-- requests under their own permission module.
--
-- Schema part generated by `prisma migrate diff` (from the migrations to
-- schema.prisma); the data part at the end is hand-written.
--
-- Existing EmployeeDocument.fileUrl / EmploymentContract.documentUrl
-- values (typed-in links from before uploads) are kept as they are.

-- AlterTable
ALTER TABLE "EmployeeDocument" ADD COLUMN     "fileId" INTEGER;

-- AlterTable
ALTER TABLE "EmploymentContract" ADD COLUMN     "documentFileId" INTEGER;

-- CreateTable
CREATE TABLE "StoredFile" (
    "id" SERIAL NOT NULL,
    "companyId" INTEGER NOT NULL,
    "purpose" TEXT NOT NULL,
    "originalName" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    "sha256" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "uploadedById" INTEGER,
    "uploadedByName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StoredFile_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "StoredFile_storageKey_key" ON "StoredFile"("storageKey");

-- CreateIndex
CREATE INDEX "StoredFile_companyId_idx" ON "StoredFile"("companyId");

-- CreateIndex
CREATE INDEX "StoredFile_createdAt_idx" ON "StoredFile"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "EmployeeDocument_fileId_key" ON "EmployeeDocument"("fileId");

-- CreateIndex
CREATE UNIQUE INDEX "EmploymentContract_documentFileId_key" ON "EmploymentContract"("documentFileId");

-- AddForeignKey
ALTER TABLE "EmployeeDocument" ADD CONSTRAINT "EmployeeDocument_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "StoredFile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmploymentContract" ADD CONSTRAINT "EmploymentContract_documentFileId_fkey" FOREIGN KEY ("documentFileId") REFERENCES "StoredFile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StoredFile" ADD CONSTRAINT "StoredFile_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- Data: the new `leaveRequests` permission module starts as a copy of each
-- role's `hr` grants, so everyone keeps exactly the leave access they had
-- (an admin can then split apply / approve on the Roles page). Roles with
-- no `hr` row get no `leaveRequests` row, which means no access — as before.
INSERT INTO "Permission" ("roleId", "module", "canView", "canAdd", "canEdit", "canDelete")
SELECT "roleId", 'leaveRequests', "canView", "canAdd", "canEdit", "canDelete"
FROM "Permission"
WHERE "module" = 'hr'
ON CONFLICT ("roleId", "module") DO NOTHING;

-- The same for API keys, whose grants are a JSON array of scopes.
UPDATE "ApiKey" AS k
SET "scopes" = k."scopes" || (
  SELECT jsonb_agg(jsonb_set(s, '{module}', '"leaveRequests"'))
  FROM jsonb_array_elements(k."scopes") AS s
  WHERE s->>'module' = 'hr'
)
WHERE jsonb_typeof(k."scopes") = 'array'
  AND EXISTS (SELECT 1 FROM jsonb_array_elements(k."scopes") AS s WHERE s->>'module' = 'hr')
  AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(k."scopes") AS s WHERE s->>'module' = 'leaveRequests');
