-- Production hardening: declare the foreign keys that were only implied by
-- column names, add the indexes lists filter on, and add CHECK constraints
-- for rules the API now enforces (so other writers can't break them either).
--
-- The CreateIndex / AddForeignKey part is generated by `prisma migrate diff`;
-- the data clean-up before it and the CHECK constraints after it are
-- hand-written.

-- Data, before the foreign keys can be added: these columns were never
-- checked, so a value may point at nothing or at another company's row.
-- Such a value never meant anything to the app (nothing reads it as a
-- reference); it is cleared.
UPDATE "Employee" AS e SET "managerId" = NULL
WHERE e."managerId" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "Employee" AS m WHERE m."id" = e."managerId" AND m."companyId" = e."companyId");
UPDATE "Department" AS d SET "managerId" = NULL
WHERE d."managerId" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "Employee" AS m WHERE m."id" = d."managerId" AND m."companyId" = d."companyId");
UPDATE "ApiKey" AS k SET "createdById" = NULL
WHERE k."createdById" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "User" AS u WHERE u."id" = k."createdById" AND u."companyId" = k."companyId");
UPDATE "StoredFile" AS f SET "uploadedById" = NULL
WHERE f."uploadedById" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM "User" AS u WHERE u."id" = f."uploadedById" AND u."companyId" = f."companyId");

-- CreateIndex
CREATE INDEX "ApiKey_createdById_idx" ON "ApiKey"("createdById");

-- CreateIndex
CREATE INDEX "CargoType_status_idx" ON "CargoType"("status");

-- CreateIndex
CREATE INDEX "Department_managerId_idx" ON "Department"("managerId");

-- CreateIndex
CREATE INDEX "Employee_managerId_idx" ON "Employee"("managerId");

-- CreateIndex
CREATE INDEX "LoadingOrder_cargoTypeId_idx" ON "LoadingOrder"("cargoTypeId");

-- CreateIndex
CREATE INDEX "LoadingOrder_pickupLocationId_idx" ON "LoadingOrder"("pickupLocationId");

-- CreateIndex
CREATE INDEX "LoadingOrder_deliveryLocationId_idx" ON "LoadingOrder"("deliveryLocationId");

-- CreateIndex
CREATE INDEX "LoadingOrder_createdAt_idx" ON "LoadingOrder"("createdAt");

-- CreateIndex
CREATE INDEX "Location_status_idx" ON "Location"("status");

-- CreateIndex
CREATE INDEX "RateContract_cargoTypeId_idx" ON "RateContract"("cargoTypeId");

-- CreateIndex
CREATE INDEX "RateContract_pickupLocationId_idx" ON "RateContract"("pickupLocationId");

-- CreateIndex
CREATE INDEX "RateContract_deliveryLocationId_idx" ON "RateContract"("deliveryLocationId");

-- CreateIndex
CREATE INDEX "StoredFile_uploadedById_idx" ON "StoredFile"("uploadedById");

-- AddForeignKey
ALTER TABLE "Department" ADD CONSTRAINT "Department_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StoredFile" ADD CONSTRAINT "StoredFile_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- CHECK constraints. Prisma's schema language has no CHECK, so they live
-- here (like the inventory ones). NOT VALID: enforced for every new or
-- changed row, without failing this migration on rows saved before the
-- rule existed (e.g. a leave request stored with reversed dates); such a
-- row must be corrected the next time it is edited.
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_dates_in_order"
  CHECK ("endDate" >= "startDate") NOT VALID;
ALTER TABLE "EmploymentContract" ADD CONSTRAINT "EmploymentContract_dates_in_order"
  CHECK ("endDate" IS NULL OR "endDate" >= "startDate") NOT VALID;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_period_in_order"
  CHECK ("toDate" >= "fromDate") NOT VALID;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_vatPercent_range"
  CHECK ("vatPercent" >= 0 AND "vatPercent" <= 100) NOT VALID;
ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_taxPercent_range"
  CHECK ("taxPercent" >= 0 AND "taxPercent" <= 100) NOT VALID;
