import { ErrorFilter } from '../models/api-response.js';

export const ErrorCode = {
  AUTH_LOGIN_FAILED: { code: 'FLEET-AUTH001', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Invalid username or password.' },
  AUTH_ACCOUNT_INACTIVE: { code: 'FLEET-AUTH002', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Your account has been deactivated. Please contact an administrator.' },
  AUTH_TOKEN_MISSING: { code: 'FLEET-AUTH003', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Authentication required. Please log in.' },
  AUTH_TOKEN_INVALID: { code: 'FLEET-AUTH004', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'Your session has expired. Please log in again.' },
  AUTH_PERMISSION_DENIED: { code: 'FLEET-AUTH005', filter: ErrorFilter.USER_NOT_AUTHORIZED, description: 'You do not have permission to perform this action.' },
  AUTH_API_KEY_INVALID: { code: 'FLEET-AUTH007', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'The API key is invalid or has been revoked.' },
  AUTH_COMPANY_INACTIVE: { code: 'FLEET-AUTH008', filter: ErrorFilter.USER_NOT_AUTHENTICATED, description: 'This company account is not active. Please contact support.' },
  AUTH_TOO_MANY_ATTEMPTS: { code: 'FLEET-AUTH006', filter: ErrorFilter.RATE_LIMIT_EXCEEDED, description: 'Too many failed sign-in attempts. Please wait a few minutes and try again.' },

  USR_DUPLICATE_EMAIL: { code: 'FLEET-USR001', filter: ErrorFilter.INVALID_REQUEST, description: 'A user with this email already exists.' },
  USR_DUPLICATE_USERNAME: { code: 'FLEET-USR002', filter: ErrorFilter.INVALID_REQUEST, description: 'A user with this username already exists.' },
  USR_NOT_FOUND: { code: 'FLEET-USR003', filter: ErrorFilter.INVALID_REQUEST, description: 'User not found.' },
  USR_CREATE_FAILED: { code: 'FLEET-USR004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create user. Please try again.' },
  USR_UPDATE_FAILED: { code: 'FLEET-USR005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update user. Please try again.' },
  USR_DELETE_FAILED: { code: 'FLEET-USR006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete user. Please try again.' },
  USR_FETCH_FAILED: { code: 'FLEET-USR007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve users. Please try again.' },
  USR_CANNOT_REMOVE_SELF: { code: 'FLEET-USR009', filter: ErrorFilter.USER_END_VIOLATION, description: 'You cannot delete or deactivate your own account.' },
  USR_PASSWORD_TOO_SHORT: { code: 'FLEET-USR010', filter: ErrorFilter.INVALID_REQUEST, description: 'Password must be at least 8 characters long.' },
  USR_LANGUAGE_UPDATE_FAILED: { code: 'FLEET-USR008', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update language preference. Please try again.' },

  TRK_NOT_FOUND: { code: 'FLEET-TRK001', filter: ErrorFilter.INVALID_REQUEST, description: 'Truck not found.' },
  TRK_IN_USE: { code: 'FLEET-TRK002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This truck is used by one or more trips and cannot be deleted.' },
  TRK_CREATE_FAILED: { code: 'FLEET-TRK003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create truck. Please try again.' },
  TRK_UPDATE_FAILED: { code: 'FLEET-TRK004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update truck. Please try again.' },
  TRK_DELETE_FAILED: { code: 'FLEET-TRK005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete truck. Please try again.' },
  TRK_FETCH_FAILED: { code: 'FLEET-TRK006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve trucks. Please try again.' },
  TRK_ASSIGNMENT_NOT_FOUND: { code: 'FLEET-TRK007', filter: ErrorFilter.INVALID_REQUEST, description: 'Truck assignment not found.' },
  TRK_ASSIGNMENT_OVERLAP: { code: 'FLEET-TRK008', filter: ErrorFilter.USER_END_VIOLATION, description: 'This truck already has an assignment during the selected period.' },
  TRK_ASSIGNMENT_INVALID_DATES: { code: 'FLEET-TRK009', filter: ErrorFilter.INVALID_REQUEST, description: 'The end date must be on or after the start date.' },
  TRK_ASSIGNMENT_FETCH_FAILED: { code: 'FLEET-TRK010', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve truck assignments. Please try again.' },
  TRK_ASSIGNMENT_CREATE_FAILED: { code: 'FLEET-TRK011', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create truck assignment. Please try again.' },
  TRK_ASSIGNMENT_UPDATE_FAILED: { code: 'FLEET-TRK012', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update truck assignment. Please try again.' },
  TRK_ASSIGNMENT_DELETE_FAILED: { code: 'FLEET-TRK013', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to remove truck assignment. Please try again.' },

  DRV_NOT_FOUND: { code: 'FLEET-DRV001', filter: ErrorFilter.INVALID_REQUEST, description: 'Driver not found.' },
  DRV_IN_USE: { code: 'FLEET-DRV002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This driver is used by one or more trips and cannot be deleted.' },
  DRV_CREATE_FAILED: { code: 'FLEET-DRV003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create driver. Please try again.' },
  DRV_UPDATE_FAILED: { code: 'FLEET-DRV004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update driver. Please try again.' },
  DRV_DELETE_FAILED: { code: 'FLEET-DRV005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete driver. Please try again.' },
  DRV_FETCH_FAILED: { code: 'FLEET-DRV006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve drivers. Please try again.' },

  CUS_NOT_FOUND: { code: 'FLEET-CUS001', filter: ErrorFilter.INVALID_REQUEST, description: 'Customer not found.' },
  CUS_IN_USE: { code: 'FLEET-CUS002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This customer is used by one or more trips and cannot be deleted.' },
  CUS_CREATE_FAILED: { code: 'FLEET-CUS003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create customer. Please try again.' },
  CUS_UPDATE_FAILED: { code: 'FLEET-CUS004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update customer. Please try again.' },
  CUS_DELETE_FAILED: { code: 'FLEET-CUS005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete customer. Please try again.' },
  CUS_FETCH_FAILED: { code: 'FLEET-CUS006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve customers. Please try again.' },

  SUP_NOT_FOUND: { code: 'FLEET-SUP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Supplier not found.' },
  SUP_IN_USE: { code: 'FLEET-SUP002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This supplier is used by one or more rate contracts and cannot be deleted.' },
  SUP_CREATE_FAILED: { code: 'FLEET-SUP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create supplier. Please try again.' },
  SUP_UPDATE_FAILED: { code: 'FLEET-SUP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update supplier. Please try again.' },
  SUP_DELETE_FAILED: { code: 'FLEET-SUP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete supplier. Please try again.' },
  SUP_FETCH_FAILED: { code: 'FLEET-SUP006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve suppliers. Please try again.' },

  LOC_NOT_FOUND: { code: 'FLEET-LOC001', filter: ErrorFilter.INVALID_REQUEST, description: 'Location not found.' },
  LOC_IN_USE: { code: 'FLEET-LOC002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This location is used by one or more trips and cannot be deleted.' },
  LOC_CREATE_FAILED: { code: 'FLEET-LOC003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create location. Please try again.' },
  LOC_UPDATE_FAILED: { code: 'FLEET-LOC004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update location. Please try again.' },
  LOC_DELETE_FAILED: { code: 'FLEET-LOC005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete location. Please try again.' },
  LOC_FETCH_FAILED: { code: 'FLEET-LOC006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve locations. Please try again.' },

  CGO_NOT_FOUND: { code: 'FLEET-CGO001', filter: ErrorFilter.INVALID_REQUEST, description: 'Cargo type not found.' },
  CGO_IN_USE: { code: 'FLEET-CGO002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This cargo type is used by one or more trips and cannot be deleted.' },
  CGO_CREATE_FAILED: { code: 'FLEET-CGO003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create cargo type. Please try again.' },
  CGO_UPDATE_FAILED: { code: 'FLEET-CGO004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update cargo type. Please try again.' },
  CGO_DELETE_FAILED: { code: 'FLEET-CGO005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete cargo type. Please try again.' },
  CGO_FETCH_FAILED: { code: 'FLEET-CGO006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve cargo types. Please try again.' },

  TRP_NOT_FOUND: { code: 'FLEET-TRP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Trip not found.' },
  TRP_CREATE_FAILED: { code: 'FLEET-TRP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create trip. Please try again.' },
  TRP_UPDATE_FAILED: { code: 'FLEET-TRP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update trip. Please try again.' },
  TRP_DELETE_FAILED: { code: 'FLEET-TRP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete trip. Please try again.' },
  TRP_FETCH_FAILED: { code: 'FLEET-TRP006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve trips. Please try again.' },
  TRP_DUPLICATE_TRANSACTION: { code: 'FLEET-TRP007', filter: ErrorFilter.INVALID_REQUEST, description: 'A trip with this transaction number already exists.' },

  INV_NOT_FOUND: { code: 'FLEET-INV001', filter: ErrorFilter.INVALID_REQUEST, description: 'Invoice not found.' },
  INV_STATUS_CONFLICT: { code: 'FLEET-INV002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This action cannot be performed on the current invoice status.' },
  INV_CREATE_FAILED: { code: 'FLEET-INV003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create invoice. Please try again.' },
  INV_UPDATE_FAILED: { code: 'FLEET-INV004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update invoice. Please try again.' },
  INV_DELETE_FAILED: { code: 'FLEET-INV005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete invoice. Please try again.' },
  INV_INVALID_LINES: { code: 'FLEET-INV007', filter: ErrorFilter.INVALID_REQUEST, description: 'Each line item needs a description, a quantity above zero and a valid rate.' },
  INV_NO_LINES: { code: 'FLEET-INV008', filter: ErrorFilter.INVALID_REQUEST, description: 'An invoice needs at least one line item.' },
  INV_LOCKED: { code: 'FLEET-INV010', filter: ErrorFilter.USER_END_VIOLATION, description: 'This invoice has been submitted to ZATCA and its amounts can no longer be changed.' },
  INV_FETCH_FAILED: { code: 'FLEET-INV006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve invoices. Please try again.' },

  RLC_NOT_FOUND: { code: 'FLEET-RLC001', filter: ErrorFilter.INVALID_REQUEST, description: 'Rate contract not found.' },
  RLC_DUPLICATE: { code: 'FLEET-RLC002', filter: ErrorFilter.INVALID_REQUEST, description: 'A rate contract with this reference already exists.' },
  RLC_CREATE_FAILED: { code: 'FLEET-RLC003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create rate contract. Please try again.' },
  RLC_UPDATE_FAILED: { code: 'FLEET-RLC004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update rate contract. Please try again.' },
  RLC_DELETE_FAILED: { code: 'FLEET-RLC005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete rate contract. Please try again.' },
  RLC_FETCH_FAILED: { code: 'FLEET-RLC006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve rate contracts. Please try again.' },

  LDO_BATCH_NOT_FOUND: { code: 'FLEET-LDO002', filter: ErrorFilter.INVALID_REQUEST, description: 'Loading order batch not found.' },
  LDO_CREATE_FAILED: { code: 'FLEET-LDO003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create loading order. Please try again.' },
  LDO_DELETE_FAILED: { code: 'FLEET-LDO005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete loading order. Please try again.' },
  LDO_DOCUMENT_FAILED: { code: 'FLEET-LDO007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to prepare the loading order document. Please try again.' },
  LDO_FETCH_FAILED: { code: 'FLEET-LDO006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve loading orders. Please try again.' },

  SPP_NOT_FOUND: { code: 'FLEET-SPP001', filter: ErrorFilter.INVALID_REQUEST, description: 'Supplier payment not found.' },
  SPP_CREATE_FAILED: { code: 'FLEET-SPP002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create supplier payment. Please try again.' },
  SPP_UPDATE_FAILED: { code: 'FLEET-SPP003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update supplier payment. Please try again.' },
  SPP_DELETE_FAILED: { code: 'FLEET-SPP004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete supplier payment. Please try again.' },
  SPP_FETCH_FAILED: { code: 'FLEET-SPP005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve supplier payments. Please try again.' },

  ROL_NOT_FOUND: { code: 'FLEET-ROL001', filter: ErrorFilter.INVALID_REQUEST, description: 'Role not found.' },
  ROL_HAS_USERS: { code: 'FLEET-ROL002', filter: ErrorFilter.USER_END_VIOLATION, description: 'This role is assigned to one or more users and cannot be deleted.' },
  ROL_CREATE_FAILED: { code: 'FLEET-ROL004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create role. Please try again.' },
  ROL_UPDATE_FAILED: { code: 'FLEET-ROL005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update role. Please try again.' },
  ROL_DELETE_FAILED: { code: 'FLEET-ROL006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete role. Please try again.' },
  ROL_PROTECTED: { code: 'FLEET-ROL008', filter: ErrorFilter.USER_END_VIOLATION, description: 'The ADMIN role is built in and cannot be renamed or deleted.' },
  ROL_UNKNOWN_MODULE: { code: 'FLEET-ROL009', filter: ErrorFilter.INVALID_REQUEST, description: 'The permission matrix contains an unknown module.' },
  ROL_DUPLICATE_NAME: { code: 'FLEET-ROL010', filter: ErrorFilter.INVALID_REQUEST, description: 'A role with this name already exists.' },
  ROL_FETCH_FAILED: { code: 'FLEET-ROL007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve roles. Please try again.' },

  DSH_HR_FETCH_FAILED: { code: 'FLEET-DSH002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load HR dashboard data. Please try again.' },
  DSH_FETCH_FAILED: { code: 'FLEET-DSH001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load dashboard data. Please try again.' },

  SET_FETCH_FAILED: { code: 'FLEET-SET001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve company settings. Please try again.' },
  SET_UPDATE_FAILED: { code: 'FLEET-SET002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update company settings. Please try again.' },

  WKS_NOT_FOUND: { code: 'FLEET-WKS001', filter: ErrorFilter.INVALID_REQUEST, description: 'Work order not found.' },
  WKS_CREATE_FAILED: { code: 'FLEET-WKS003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create work order. Please try again.' },
  WKS_UPDATE_FAILED: { code: 'FLEET-WKS004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update work order. Please try again.' },
  WKS_DELETE_FAILED: { code: 'FLEET-WKS005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete work order. Please try again.' },
  WKS_FETCH_FAILED: { code: 'FLEET-WKS006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve work orders. Please try again.' },
  WKS_MNT_NOT_FOUND: { code: 'FLEET-WKS007', filter: ErrorFilter.INVALID_REQUEST, description: 'Maintenance schedule not found.' },
  WKS_MNT_CREATE_FAILED: { code: 'FLEET-WKS008', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create maintenance schedule. Please try again.' },
  WKS_MNT_UPDATE_FAILED: { code: 'FLEET-WKS009', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update maintenance schedule. Please try again.' },
  WKS_MNT_DELETE_FAILED: { code: 'FLEET-WKS010', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete maintenance schedule. Please try again.' },
  WKS_MNT_FETCH_FAILED: { code: 'FLEET-WKS011', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve maintenance schedules. Please try again.' },
  WKS_INS_CREATE_FAILED: { code: 'FLEET-WKS012', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create inspection. Please try again.' },
  WKS_INS_FETCH_FAILED: { code: 'FLEET-WKS013', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve inspections. Please try again.' },
  WKS_INS_NOT_FOUND: { code: 'FLEET-WKS026', filter: ErrorFilter.INVALID_REQUEST, description: 'Inspection not found.' },
  WKS_INS_DELETE_FAILED: { code: 'FLEET-WKS021', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete inspection. Please try again.' },
  WKS_EXP_CREATE_FAILED: { code: 'FLEET-WKS022', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create workshop expense. Please try again.' },
  WKS_EXP_FETCH_FAILED: { code: 'FLEET-WKS023', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve workshop expenses. Please try again.' },
  WKS_INS_UPDATE_FAILED: { code: 'FLEET-WKS027', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update inspection. Please try again.' },
  WKS_EXP_NOT_FOUND: { code: 'FLEET-WKS029', filter: ErrorFilter.INVALID_REQUEST, description: 'Workshop expense not found.' },
  WKS_EXP_UPDATE_FAILED: { code: 'FLEET-WKS030', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update workshop expense. Please try again.' },
  WKS_EXP_DELETE_FAILED: { code: 'FLEET-WKS031', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete workshop expense. Please try again.' },
  WKS_PART_NOT_FOUND: { code: 'FLEET-WKS032', filter: ErrorFilter.INVALID_REQUEST, description: 'Work order part not found.' },
  WKS_HAS_INVENTORY: { code: 'FLEET-WKS036', filter: ErrorFilter.USER_END_VIOLATION, description: 'This work order has inventory used on it. Remove those items first (Inventory used) so their stock goes back to the warehouse, then delete the work order.' },
  WKS_INS_ITEM_NOT_FOUND: { code: 'FLEET-WKS033', filter: ErrorFilter.INVALID_REQUEST, description: 'Inspection item not found.' },
  WKS_DASH_FETCH_FAILED: { code: 'FLEET-WKS024', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load workshop dashboard data. Please try again.' },

  STK_WH_NOT_FOUND: { code: 'FLEET-STK001', filter: ErrorFilter.INVALID_REQUEST, description: 'Warehouse not found.' },
  STK_WH_CREATE_FAILED: { code: 'FLEET-STK002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create warehouse. Please try again.' },
  STK_WH_UPDATE_FAILED: { code: 'FLEET-STK003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update warehouse. Please try again.' },
  STK_WH_DELETE_FAILED: { code: 'FLEET-STK004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete warehouse. Please try again.' },
  STK_WH_FETCH_FAILED: { code: 'FLEET-STK005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve warehouses. Please try again.' },
  STK_WH_DUPLICATE: { code: 'FLEET-STK006', filter: ErrorFilter.INVALID_REQUEST, description: 'A warehouse with this name already exists.' },
  STK_WH_IN_USE: { code: 'FLEET-STK007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This warehouse has stock or stock history and cannot be deleted. Set it to inactive instead.' },
  STK_ITEM_NOT_FOUND: { code: 'FLEET-STK008', filter: ErrorFilter.INVALID_REQUEST, description: 'Inventory item not found.' },
  STK_ITEM_CREATE_FAILED: { code: 'FLEET-STK009', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create inventory item. Please try again.' },
  STK_ITEM_UPDATE_FAILED: { code: 'FLEET-STK010', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update inventory item. Please try again.' },
  STK_ITEM_DELETE_FAILED: { code: 'FLEET-STK011', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete inventory item. Please try again.' },
  STK_ITEM_FETCH_FAILED: { code: 'FLEET-STK012', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve inventory items. Please try again.' },
  STK_ITEM_DUPLICATE: { code: 'FLEET-STK013', filter: ErrorFilter.INVALID_REQUEST, description: 'An inventory item with this item number already exists.' },
  STK_ITEM_IN_USE: { code: 'FLEET-STK014', filter: ErrorFilter.USER_END_VIOLATION, description: 'This item has stock or stock history and cannot be deleted. Set it to discontinued instead.' },
  STK_INSUFFICIENT: { code: 'FLEET-STK015', filter: ErrorFilter.USER_END_VIOLATION, description: 'Not enough stock of this item in the selected warehouse.' },
  STK_MOVE_FAILED: { code: 'FLEET-STK016', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to record the stock movement. Please try again.' },
  STK_STOCK_FETCH_FAILED: { code: 'FLEET-STK017', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve stock levels. Please try again.' },
  STK_MOVE_FETCH_FAILED: { code: 'FLEET-STK018', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve stock movements. Please try again.' },
  STK_DASH_FETCH_FAILED: { code: 'FLEET-STK019', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to load inventory dashboard data. Please try again.' },

  HR_NOT_FOUND: { code: 'FLEET-HR001', filter: ErrorFilter.INVALID_REQUEST, description: 'Record not found.' },
  HR_DUPLICATE: { code: 'FLEET-HR002', filter: ErrorFilter.INVALID_REQUEST, description: 'A record with this information already exists.' },
  HR_CREATE_FAILED: { code: 'FLEET-HR003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create record. Please try again.' },
  HR_UPDATE_FAILED: { code: 'FLEET-HR004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to update record. Please try again.' },
  HR_DELETE_FAILED: { code: 'FLEET-HR005', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to delete record. Please try again.' },
  HR_FETCH_FAILED: { code: 'FLEET-HR006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve records. Please try again.' },
  HR_IN_USE: { code: 'FLEET-HR007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This record is referenced by other records and cannot be deleted.' },
  HR_ATTENDANCE_DUPLICATE: { code: 'FLEET-HR008', filter: ErrorFilter.INVALID_REQUEST, description: 'Attendance already recorded for this employee on this date.' },
  HR_LEAVE_DECISION_DENIED: {
    code: 'FLEET-HR009',
    filter: ErrorFilter.USER_NOT_AUTHORIZED,
    description: 'New leave requests start as Pending. Only a role allowed to approve leave (Leave requests: Edit) can set Approved or Rejected.',
  },
  HR_ATTENDANCE_TIMES: { code: 'FLEET-HR010', filter: ErrorFilter.INVALID_REQUEST, description: 'Time out must be after time in, and within 24 hours of it.' },

  FIL_MISSING: { code: 'FLEET-FIL001', filter: ErrorFilter.INVALID_REQUEST, description: 'Choose a file to upload.' },
  FIL_TOO_LARGE: { code: 'FLEET-FIL002', filter: ErrorFilter.INVALID_REQUEST, description: 'The file is too large.' },
  FIL_TYPE_NOT_ALLOWED: { code: 'FLEET-FIL003', filter: ErrorFilter.INVALID_REQUEST, description: 'Only PDF files and images (JPEG, PNG or WebP) can be uploaded.' },
  FIL_NOT_FOUND: { code: 'FLEET-FIL004', filter: ErrorFilter.INVALID_REQUEST, description: 'File not found.' },
  FIL_LINK_INVALID: { code: 'FLEET-FIL005', filter: ErrorFilter.USER_NOT_AUTHORIZED, description: 'This file link has expired. Open the file again from its record.' },
  FIL_UPLOAD_FAILED: { code: 'FLEET-FIL006', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to upload the file. Please try again.' },
  FIL_READ_FAILED: { code: 'FLEET-FIL007', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to open the file. Please try again.' },
  FIL_ALREADY_ATTACHED: { code: 'FLEET-FIL008', filter: ErrorFilter.USER_END_VIOLATION, description: 'This file is already attached to another record. Upload it again for this one.' },
  FIL_WRONG_PURPOSE: { code: 'FLEET-FIL009', filter: ErrorFilter.INVALID_REQUEST, description: 'This file was uploaded for a different kind of record.' },
  FIL_INVALID_PURPOSE: { code: 'FLEET-FIL010', filter: ErrorFilter.INVALID_REQUEST, description: 'Unknown upload type.' },
  FIL_NOT_MULTIPART: { code: 'FLEET-FIL011', filter: ErrorFilter.INVALID_REQUEST, description: 'Send the file as multipart/form-data, in a field named "file".' },
  FIL_ENDPOINT_NOT_FOUND: { code: 'FLEET-FIL012', filter: ErrorFilter.INVALID_REQUEST, description: 'There is no such file operation.' },

  ZATCA_ALREADY_SUBMITTED: { code: 'FLEET-ZATCA003', filter: ErrorFilter.USER_END_VIOLATION, description: 'This invoice has already been submitted to ZATCA.' },
  ZATCA_SUBMIT_FAILED: { code: 'FLEET-ZATCA004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Failed to submit invoice to ZATCA. Please try again.' },

  SYS_UNEXPECTED: { code: 'FLEET-SYS001', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Something went wrong. Please try again.' },
  SYS_VALIDATION_ERROR: { code: 'FLEET-SYS002', filter: ErrorFilter.INVALID_REQUEST, description: 'The request contains invalid data.' },
  SYS_IDEMPOTENCY_KEY_REUSED: { code: 'FLEET-SYS009', filter: ErrorFilter.INVALID_REQUEST, description: 'This Idempotency-Key was already used with a different request.' },
  SYS_IDEMPOTENCY_IN_PROGRESS: { code: 'FLEET-SYS010', filter: ErrorFilter.USER_END_VIOLATION, description: 'This request is already being processed. Please wait a moment.' },
  SYS_DUPLICATE: { code: 'FLEET-SYS005', filter: ErrorFilter.INVALID_REQUEST, description: 'A record with the same unique value already exists.' },
  SYS_INVALID_REFERENCE: { code: 'FLEET-SYS006', filter: ErrorFilter.INVALID_REQUEST, description: 'One of the selected related records does not exist.' },
  SYS_RECORD_IN_USE: { code: 'FLEET-SYS007', filter: ErrorFilter.USER_END_VIOLATION, description: 'This record is used by other records and cannot be deleted.' },
  SYS_RECORD_NOT_FOUND: { code: 'FLEET-SYS008', filter: ErrorFilter.INVALID_REQUEST, description: 'The requested record no longer exists.' },

  APK_NOT_FOUND: { code: 'FLEET-APK001', filter: ErrorFilter.INVALID_REQUEST, description: 'API key not found.' },
  APK_CREATE_FAILED: { code: 'FLEET-APK002', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to create API key. Please try again.' },
  APK_REVOKE_FAILED: { code: 'FLEET-APK003', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to revoke API key. Please try again.' },
  APK_INVALID_SCOPE: { code: 'FLEET-APK005', filter: ErrorFilter.INVALID_REQUEST, description: 'The API key permissions contain an unknown, repeated or non-grantable module.' },
  APK_SCOPE_EXCEEDS_CREATOR: { code: 'FLEET-APK006', filter: ErrorFilter.USER_NOT_AUTHORIZED, description: 'You cannot grant an API key a permission you do not have yourself.' },
  APK_NO_SCOPES: { code: 'FLEET-APK007', filter: ErrorFilter.INVALID_REQUEST, description: 'Select at least one permission for the API key.' },
  APK_FETCH_FAILED: { code: 'FLEET-APK004', filter: ErrorFilter.TECHNICAL_ISSUE, description: 'Unable to retrieve API keys. Please try again.' },

  /** The standard rate-limit code; the description is rewritten per response with the actual wait time. */
  RATE_LIMITED: { code: 'RATE-429001', filter: ErrorFilter.RATE_LIMIT_EXCEEDED, description: 'Too many requests. Please try again later.' },
} as const;
